{% set name = "hyperlink" %}
{% set version = "21.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 427af957daa58bc909471c6c40f74c5450fa123dd093fc53efd2e91d2705a56b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - idna >=2.6

test:
  imports:
    - hyperlink

about:
  home: https://github.com/python-hyper/hyperlink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Immutable, Pythonic, correct URLs.
  dev_url: https://github.com/python-hyper/hyperlink
  doc_url: http://hyperlink.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
