{% set name = "hyperlink" %}
{% set version = "20.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47fcc7cd339c6cb2444463ec3277bdcfe142c8b1daf2160bdd52248deec815af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - idna >=2.6

test:
  imports:
    - hyperlink

about:
  home: https://github.com/python-hyper/hyperlink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Immutable, Pythonic, correct URLs.
  dev_url: https://github.com/python-hyper/hyperlink
  doc_url: http://hyperlink.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
