context:
  name: hyperlink
  version: 21.0.0
  python_min: "3.9"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 427af957daa58bc909471c6c40f74c5450fa123dd093fc53efd2e91d2705a56b

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - idna >=2.6

tests:
  - python:
      imports:
        - hyperlink
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  summary: Immutable, Pythonic, correct URLs.
  homepage: https://github.com/python-hyper/hyperlink
  repository: https://github.com/python-hyper/hyperlink
  documentation: http://hyperlink.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - isuruf
    - synapticarbors
