travis:
  secure:
    BINSTAR_TOKEN: EIH26BR3B9Hx4Za6zmQwtMl+hg9Pxy/67WRbxPDEPID3cvxIgnSG8vhtG0waKDQxj+zC6bxhW4aukXxskGaFI0kyKfU7tDON6GYYkdW5+aocmfBNK983e9TROiagCgK5tdiy3eO15di6Jnjk8zrfyptNsRLyZcRNyD/HPoUGZqVwZ1eUaIAHo6qkBMxXm26IzD7NqXN8jlrVnyjq0eR1m2V+C0N49HA1IozvpRe0UvHHTlyGQvnOTJ2v3PPtdMF3F6BQflwCm4SVql1bTtAp2QL0ILkYljYKI5kwv5Ef0aRjgOgnXTdVywXxY4EURt1VUWO+KZrpTLnEckeBdBqdVZltXMa4YrOpvR6dseG4lefYH8c75/gU6//qIvFWUELCYUb/bicr7SfFfKLPiYcm3uKT1Dxwg+m+r3RUtK0U8PI5MNDK7Ssg669Ag6C4+TQG4/9AnEgf8CVFFri9pPLm2uzu187YGZnKaGARkG75NMwhDGC8Qumoo4O4hVAKMmQMWDYW13Cem4ytbajCQ+dRva17Nz79hP2Mnwl3bqSSlJ5KV8AAkt8NPiNPB77bC2Yb0xnCEvE1ghgVKrbTj4s6KMu6xKniCgTQbpH/lpeepyGnzM8lX7XGhP1LWH6UG0BdFYViIpaRuoiLQnS7Joa8uVInZ/mfX08zUWAUluHhcBM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
